# Generado automáticamente por Matugen
$bg_dark        = rgb(111318)
$surface        = rgba(1d2024b3)
$surface_bright = rgba(282a2fcc)
$accent         = rgb(a6c8ff)
$accent_glow    = rgba(a6c8ff59)
$text_main      = rgb(e1e2e9)
$text_muted     = rgb(8d9199)
$error_color    = rgb(ffb4ab)
