[colors.primary]
background = '#151314'
foreground = '#e8e1e2'

[colors.cursor]
text = '#151314'
cursor = '#e8e1e2'

[colors.vi_mode_cursor]
text = '#151314'
cursor = '#ddbecd'

[colors.search.matches]
foreground = '#4d4448'
background = '#e6beb4'

[colors.search.focused_match]
foreground = '#4d4448'
background = '#ddbecd'

[colors.footer_bar]
foreground = '#4d4448'
background = '#e8e1e2'

[colors.hints.start]
foreground = '#4d4448'
background = '#d3c2c9'

[colors.hints.end]
foreground = '#4d4448'
background = '#d3c2c9'

[colors.selection]
text = '#d0c3c8'
background = '#4d4448'


[colors.normal]
black   = '#4d4448'
red     = '#ffb4ab'
green   = '#ddbecd'
yellow  = '#d3c2c9'
blue    = '#e6beb4'
magenta = '#ddbecd'
cyan    = '#d3c2c9'
white   = '#e8e1e2'


[colors.bright]
black   = '#998e92'
red     = '#ffb4ab'
green   = '#ddbecd'
yellow  = '#d3c2c9'
blue    = '#e6beb4'
magenta = '#ddbecd'
cyan    = '#d3c2c9'
white   = '#e8e1e2'


[colors.dim]
black   = '#4d4448'
red     = '#ffb4ab'
green   = '#ddbecd'
yellow  = '#d3c2c9'
blue    = '#e6beb4'
magenta = '#ddbecd'
cyan    = '#d3c2c9'
white   = '#e8e1e2'
