# ===== CONFIGS ALACRITTY =====

[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[font]
size = 9.36

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.15
#style = "Beam"      # Block | Underline | Beam
#blinking = "On"         # On | Off | Always | Never

[window]
opacity = 0.5
decorations = "None"

[window.padding]
x = 10
y = 8

[colors.primary]
#background = "#000000"
